### ISSUE TITLE
Training on mutliple GPUs

### ISSUE THREAD

**Issue by khawar-islam** [mindee/doctr#1146]
### 🚀 The feature

I am trying to implement multiple GPUS via DataParallel, unfortunately all doctr members are busy.

### Motivation, pitch

When we have a large-scale dataset it hard to train on single GPUs that's why we need multiple GPUs code.

**Comment by felixdittrich92** [comment]
Hi @khawar-islam :wave:,

i totally agree with your feature request we should add this option to all training scripts :+1: 
Unfortunally i do not have the spare time to implement it currently :/

Maybe @odulcy-mindee can help ?

**Comment by khawar-islam** [comment]
Hello @felixdittrich92, I was completely stuck in it and merging dataset problem for almost one and half months only you are supporting me and give me answers that's why I tag you again and again. Please @odulcy-mindee help me, I already implemented the DataParallel code, and there some small related to docTR library

**Comment by aminemindee** [comment]
Hello @khawar-islam i saw your message on our slack community and the issue here. I agree it's something that can be really useful to add in doctr however we don't have the time to deal with it at the moment. 

From what i saw in your stackoverflow question (https://stackoverflow.com/questions/75431017/pytorch-multiple-gpus-attributeerror-list-object-has-no-attribute-to). from what i understand you need to just remove the part where you put also the targets on the device i think it's done inside the model.  ( i'm not an expert on running on multiple gpus but that's what i understood)

For your merging dataset, i think you can find a solution here: (https://stackoverflow.com/a/67163131)

**Comment by khawar-islam** [comment]
Hello @aminemindee, I tried to remove `.to(target)` variable but at last it didn't work for me and I cannot utilize multiple GPUS.
Is there anyone who can support me?

I have an idea about merging datasets but @felixdittrich92 recommends me it combines three datasets (mine dataset+MJSynth+SynthText). The below code does not work properly 

`https://github.com/mindee/doctr/discussions/1103
`
```
 custom_train_set = RecognitionDataset(
            parts[0].joinpath("images"),
            parts[0].joinpath("labels.json"),
            img_transforms=Compose(
                [
                    T.Resize((args.input_size, 4 * args.input_size), preserve_aspect_ratio=True),
                    # Augmentations
                    T.RandomApply(T.ColorInversion(), 0.1),
                    ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3, hue=0.02),
                ]
            ),
        )
        if len(parts) > 1:
            for subfolder in parts[1:]:
                custom_train_set.merge_dataset(
                    RecognitionDataset(subfolder.joinpath("images"), subfolder.joinpath("labels.json"))
                )

        train_set = MJSynth(
            train=True,
            img_folder='/media/cvpr/CM_22/mjsynth/mnt/ramdisk/max/90kDICT32px',
            label_path='/media/cvpr/CM_22/mjsynth/mnt/ramdisk/max/90kDICT32px/imlist.txt',
            img_transforms=T.Resize((args.input_size, 4 * args.input_size), preserve_aspect_ratio=True),
        )

        _train_set = SynthText(
            train=True,
            recognition_task=True,
            download=True,  # NOTE: download can take really long depending on your bandwidth
            img_transforms=T.Resize((args.input_size, 4 * args.input_size), preserve_aspect_ratio=True),
        )
        train_set.data.extend([(np_img, target) for np_img, target in _train_set.data])
        train_set.data.extend([(np_img, target) for np_img, target in custom_train_set.data])
```

**Comment by odulcy-mindee** [comment]
Hi @khawar-islam,

Thanks for this issue! I can try to help you on multiple GPUs support.

Can you open a Draft Pull Request with the code you have written for multiple GPU support, even if it's not working at the moment ?

Thanks in advance

**Comment by khawar-islam** [comment]
Hello @odulcy-mindee,

I am sharing python file **DP_KR.py** because my experience with Pull Request is not that much good, I have followed below code to implement `DataParallel` and I have also checked below code it works fine.
`https://github.com/kuangliu/pytorch-cifar/blob/master/main.py`

[DP_KR.zip](https://github.com/mindee/doctr/files/10750744/DP_KR.zip)

**Comment by odulcy-mindee** [comment]
@khawar-islam Thanks, I'll have a look at it and see what I can do

**Comment by khawar-islam** [comment]
Dear @odulcy-mindee Do you have any feedback about code and how we can implement Data Parallel code?

**Comment by khawar-islam** [comment]
Hello @odulcy-mindee please have a look

**Comment by odulcy-mindee** [comment]
Hello @khawar-islam, sorry for the very long delay. I started a draft PR here: https://github.com/mindee/doctr/pull/1164.
It's not working yet but you'll be able to follow the progress here.

Based on what I read today, `DataParallel` seems to not to be the best solution: it suffers from GIL. I'll try with `DistributedDataParallel` which seems more appropriate because it does not suffer from GIL.
