### ISSUE TITLE
train data?

### ISSUE THREAD

**Issue by lw3259111** [mindee/doctr#271]
hello:
Where can I download the training data？

**Comment by charlesmindee** [comment]
Hi @lw3259111 , our training data is private since most of the images contain very personal and/or sensitive data: invoices, IDs, receipts, forms, contracts, ...
For now, only public test sets (FUNSD and CORD) are available on doctr, but we will probably release our own specific datasets within a few months, and add new public test sets within a few weeks.

**Comment by charlesmindee** [comment]
I am closing this issue for now, since it is inactive.
