### ISSUE TITLE
[interpolation] Investigate difference in resizing/rotation between cv2, TF & Pytorch

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#402]
The library doesn't have clear information on the consequences of image transformation using different framework backends. Some need to be investigated:
- appearance of artefacts during interpolation with some methods
- difference in interpolation results between 3 frameworks

**Comment by charlesmindee** [comment]
As mentioned [here](https://towardsdatascience.com/image-read-and-resize-with-opencv-tensorflow-and-pil-3e0f29b992be), 
cv2 uses by default bilinear interpolation with half-pixel corrections, while the bilinear resizing of tf doesn't use this half-pixel correction. The way to fix that is to pass `half_pixel_centers=True` in the `tf.image.resize_bilinear` function.
However, this tf function is deprecated in tf 2, and the new resizing function does not provide this arg. 
[this pytorch issue](https://github.com/pytorch/pytorch/issues/48389) is also mentioning this issue, and it seems that we cannot use this arg in pytorch for the moment.

**Comment by charlesmindee** [comment]
[This issue](https://github.com/pytorch/vision/issues/2950) also tackle this issue of anti-aliasing between torch and PIL. As mentionned in [this article](https://tcapelle.github.io/pytorch/fastai/2021/02/26/image_resizing.html), the arg `anti_aliasing` is now available in torchvision.

**Comment by charlesmindee** [comment]
![image](https://user-images.githubusercontent.com/70526046/131351773-93867086-ef97-4be6-aa32-597ff9405b2a.png)
This is quite a good summary, it seems that using `anti_alias=True` in tf and `anti_aliasing` in torchvision lead to ALMOST similar results.

**Comment by fg-mindee** [comment]
Alright, we almost got everything to close this issue:
- [x] Check the expected differences in interpolation between cv2, TF & PyTorch
- [x] Identify how to bring the difference down to zero (or something that can be ignored)
- [ ] Assess which models/task were trained with interpolation schemes that cannot allow zero-difference with other frameworks.
- [ ] Assess the performance impact of direct porting (without retraining)

**Comment by charlesmindee** [comment]
For the moment we used `tf.image.resize` and` torchvision.transforms.functional.resize` in all our preprocessor thus in all trainings (both reco & detection). We didn't use anti aliasing in TF nor in torch because is is disabled by default. We should use antialiasing in the future for all trainings to train our models exactly on the same pictures.

`cv2.resize` is used in `read_img_as_numpy` (which never performs resizing by default, so it is never called), in `rotate_image` (to crop straight boxes on rotated images, which we never used but in the near future we will use it since we will have rotated segmentation maps) and in the app for visualization only.

@fg-mindee

**Comment by fg-mindee** [comment]
Thanks!
So, to even everything out, we would only need to enforce anti-aliasing on TF resize for now?

If so, we could:
- start doing this in future trainings
- investigate whether this severely impact previously trained models

**Comment by fg-mindee** [comment]
We won't have time to harmonize & retrain all models with this before the next release, so I'm staging it for 0.6.0 :+1:
