### ISSUE TITLE
Doct not working on some crops

### ISSUE THREAD

**Issue by haythemBD** [mindee/doctr#631]
Hello community, I have crops from a given image on which I want to run doctr (zoo model) to recognize text. the OCR predictor returns nothing and generates some warnings during the processing. Is there any solution for this please?
![bug](https://user-images.githubusercontent.com/90775911/142076893-259833ef-1739-41aa-9a89-d3e87f19d916.jpg)

**Comment by fg-mindee** [comment]
Hi @haythemBD :wave: 

Thanks for the feedback! However we're missing quite a lot of information from the bug report template to debug properly :sweat_smile:
Could you provide the following please?
- the minimal python code snippet to reproduce this behaviour
- your environment configuration (please report the console output of the following snippet)
```
wget https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

_Next time, please follow the bug report template to this easier :)_

At first sight, this is only a warning so it should not have any significant influence on the output!

**Comment by fg-mindee** [comment]
Any update @haythemBD ? :pray:

**Comment by haythemBD** [comment]
- Hello @fg-mindee. I think that the model works really well on big images but not on small ones: for example images with 300*300 dimension.

**Comment by fg-mindee** [comment]
Alright, but we need some specifics from you so that we can do something with this issue :sweat_smile: 
That's why we created the bug report template, so that we don't have to go back & forth until we collect all required information :upside_down_face: 

As requested earlier, could you please share:
- your environment information
- the input image where you noticed this
- a minimal code snippet to reproduce the behaviour

:pray: 

With this, I'm sure we'll be able to tackle your problem :) 
Perhaps it might be worth taking a look at https://github.com/mindee/doctr/issues/639

**Comment by haythemBD** [comment]
I thin indeed it is the same problem @fg-mindee. You can close this issue

**Comment by fg-mindee** [comment]
Glad it helped! Let us know if you have additional questions :pray:
