### ISSUE TITLE
Brew installed packages are not found in Python

### ISSUE THREAD

**Issue by siamakzd** [mindee/doctr#813]
Hello,

I am trying to use doctr on MacOS and installed the extra dependencies through brew. However, when I run your basic doctr code I get errors like:

> OSError: no library called "cairo-2" was found

It seems that brew installs the packages under `/opt/brew/Cellar/` but in Python those packages are looking into `/usr/lib/`.

Do you know of any fix for this problem?

Thanks in Advance!

**Comment by fg-mindee** [comment]
Hi @siamakzd :wave: 

Thanks for reporting this!
So here are my thoughts on this:
- first option is that there was a simple issue with installing cairo (that our installation procedure didn't work for Mac in general). To check this, could you try to install cairo on your own (cf. https://macappstore.org/cairo/) and run the code snippet again?
- second option is that the above installation will fail because of your hardware. Do you happen to have an M1 chip? If so, there is a discussion about this and a community member found the way to fix this: https://github.com/mindee/doctr/discussions/749


Either way, would you mind running the environment collection script and display the console output here please? :pray: 
```shell
wget https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Cheers :v:

**Comment by fg-mindee** [comment]
Any update @siamakzd? :)

**Comment by fg-mindee** [comment]
Hello @siamakzd :wave: 

Did you manage to solve your problem?

**Comment by siamakzd** [comment]
Hello @fg-mindee 

I moved to Ubuntu and was able to install everything.

For future reference, one of the dependencies (mupdf) only works on Python >= 3.8, and won't work on the default Python 3.6.
