### ISSUE TITLE
Issue when exporting as XML

### ISSUE THREAD

**Issue by Jimchoo91** [mindee/doctr#894]
When I try to use the result.export_as_xml() method, I receive the below error:

```
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7496/3505309393.py in <module>
----> 1 xml_output = result.export_as_xml()
      2 print(xml_output[0][0])

c:\ds\tools\python3.8\latest\lib\site-packages\doctr\io\elements.py in export_as_xml(self, **kwargs)
    397             list of tuple of (bytes, ElementTree)
    398         """
--> 399         return [page.export_as_xml(**kwargs) for page in self.pages]
    400 
    401     @classmethod

c:\ds\tools\python3.8\latest\lib\site-packages\doctr\io\elements.py in <listcomp>(.0)
    397             list of tuple of (bytes, ElementTree)
    398         """
--> 399         return [page.export_as_xml(**kwargs) for page in self.pages]
    400 
    401     @classmethod

c:\ds\tools\python3.8\latest\lib\site-packages\doctr\io\elements.py in export_as_xml(self, file_title)
    288         SubElement(head, 'title').text = file_title
    289         SubElement(head, 'meta', attrib={'http-equiv': 'Content-Type', 'content': 'text/html; charset=utf-8'})
--> 290         SubElement(head, 'meta', attrib={'name': 'ocr-system', 'content': f"python-doctr {doctr.__version__}"})
    291         SubElement(head, 'meta', attrib={'name': 'ocr-capabilities',
    292                                          'content': 'ocr_page ocr_carea ocr_par ocr_line ocrx_word'})

AttributeError: module 'doctr' has no attribute '__version__'
```

Is this recognised? thanks.

**Comment by felixdittrich92** [comment]
Hi @Jimchoo91 :wave: ,

Which version do you use ? :) 
I have tested it with the current main branch and cannot reproduce this issue

**Comment by Jimchoo91** [comment]
Thanks that worked!

**Comment by charlesmindee** [comment]
Thank you @felixdittrich92 !

**Comment by nikitakor7** [comment]
This issue is resurfacing again. Here are some details:

  File "/Users/nikita/Documents/Projects/HomeBuy/homebuy/lib/python3.11/site-packages/doctr/io/elements.py", line 589, in export_as_xml
    return [page.export_as_xml(**kwargs) for page in self.pages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikita/Documents/Projects/HomeBuy/homebuy/lib/python3.11/site-packages/doctr/io/elements.py", line 589, in <listcomp>
    return [page.export_as_xml(**kwargs) for page in self.pages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikita/Documents/Projects/HomeBuy/homebuy/lib/python3.11/site-packages/doctr/io/elements.py", line 316, in export_as_xml
    attrib={"name": "ocr-system", "content": f"python-doctr {doctr.__version__}"},  # type: ignore[attr-defined]
    
  **Checked version of doctr**
"Requirement already satisfied: python-doctr[tf] in /Users/nikita/Documents/Projects/HomeBuy/homebuy/lib/python3.11/site-packages (0.8.1)"

Is there anything I am missing in here?
